"""Add new manufacturer brands and their plugins to seed.json."""

import json
from pathlib import Path

SEED_PATH = Path(__file__).resolve().parent.parent / "data" / "seed.json"

# ── New manufacturers ─────────────────────────────────────────────────────

NEW_MANUFACTURERS = [
    {
        "slug": "orchestral-tools",
        "name": "Orchestral Tools",
        "website": "https://www.orchestraltools.com"
    },
    {
        "slug": "mcdsp",
        "name": "McDSP",
        "website": "https://mcdsp.com"
    },
    {
        "slug": "korg",
        "name": "KORG",
        "website": "https://www.korg.com"
    },
    {
        "slug": "vienna-symphonic-library",
        "name": "Vienna Symphonic Library",
        "website": "https://www.vsl.co.at"
    },
    {
        "slug": "moog-music",
        "name": "Moog Music",
        "website": "https://www.moogmusic.com"
    },
]

# ── Orchestral Tools plugins ─────────────────────────────────────────────

OT_PLUGINS = [
    {
        "slug": "sine-player",
        "name": "SINE Player",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["SINE Player", "SINE", "OT SINE"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Free sample player from Orchestral Tools hosting all their orchestral libraries with selective downloads, multi-mic mixing, and customizable articulation lists.",
        "price_type": "free",
        "url": "https://www.orchestraltools.com/get-sine",
        "year": 2019,
        "tags": ["sampler", "orchestral", "sample-player", "cinematic", "film-scoring", "free"],
        "image_url": ""
    },
    {
        "slug": "berlin-strings",
        "name": "Berlin Strings",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Berlin Strings", "OT Berlin Strings"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Flagship string ensemble library with five sections, exceptional dynamic range, multiple legato modes, and bow-stroke control, recorded at Berlin's Teldex Scoring Stage.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/berlin-strings",
        "year": 2014,
        "tags": ["orchestral", "strings", "cinematic", "film-scoring", "ensemble", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "berlin-woodwinds",
        "name": "Berlin Woodwinds",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Berlin Woodwinds", "OT Berlin Woodwinds"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Detailed woodwind library with 12 individual instruments for expressive solo lines and custom ensembles, recorded at the Teldex Scoring Stage.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/berlin-woodwinds",
        "year": 2012,
        "tags": ["orchestral", "woodwinds", "cinematic", "film-scoring", "ensemble", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "berlin-brass",
        "name": "Berlin Brass",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Berlin Brass", "OT Berlin Brass"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Gold-standard orchestral brass collection featuring French horns, trumpets, trombones, and tuba with extensive articulations, recorded at the Teldex Scoring Stage.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/berlin-brass",
        "year": 2017,
        "tags": ["orchestral", "brass", "cinematic", "film-scoring", "ensemble", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "berlin-percussion",
        "name": "Berlin Percussion",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Berlin Percussion", "OT Berlin Percussion"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Comprehensive orchestral percussion collection with pitched and unpitched instruments, multiple stick options, and the complete Berlin Timpani set.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/berlin-percussion",
        "year": 2016,
        "tags": ["orchestral", "percussion", "drums", "cinematic", "film-scoring", "timpani", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "berlin-orchestra-inspire-1",
        "name": "Berlin Orchestra Inspire 1",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Berlin Inspire 1", "Berlin Inspire", "BOI 1"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Streamlined all-in-one orchestral package optimized for laptop performance, providing essential strings, brass, woodwinds, piano, and percussion from the Berlin Series.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/berlin-orchestra-inspire-1",
        "year": 2018,
        "tags": ["orchestral", "cinematic", "film-scoring", "strings", "brass", "woodwinds", "percussion", "sample-library", "starter"],
        "image_url": ""
    },
    {
        "slug": "metropolis-ark-1",
        "name": "Metropolis Ark 1",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Metropolis Ark 1", "MA1", "Metropolis Ark I"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Epic orchestral scoring toolset with huge orchestra, choir, percussion, and piano recorded at extreme fortissimo dynamics for bold cinematic music.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/metropolis-ark-1",
        "year": 2016,
        "tags": ["orchestral", "cinematic", "film-scoring", "epic", "choir", "percussion", "brass", "strings", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "ot-time-macro",
        "name": "TIME macro",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["TIME macro", "OT TIME macro"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Orchestral and choral textures collection with advanced articulations and dynamic gestures exploring time through mid-sized ensembles and layered structures.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/time-macro",
        "year": 2018,
        "tags": ["orchestral", "cinematic", "film-scoring", "textures", "atmospheric", "choir", "experimental", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "ot-time-micro",
        "name": "TIME micro",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["TIME micro", "OT TIME micro"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Atmospheric and rhythmic underscoring resource with intimate small instrument groups and soloists offering delicate orchestral textures.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/time-micro",
        "year": 2019,
        "tags": ["orchestral", "cinematic", "film-scoring", "textures", "atmospheric", "intimate", "chamber", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "ot-tallinn",
        "name": "Tallinn",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Tallinn", "OT Tallinn", "Tallinn Baltic Voices"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Baltic voices and strings library featuring the Estonian Philharmonic Chamber Choir, Tallinn Chamber Orchestra, and pipe organs recorded in Niguliste church.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/tallinn",
        "year": 2021,
        "tags": ["orchestral", "choir", "strings", "vocal", "cinematic", "film-scoring", "nordic", "chamber", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "ot-phoenix-orchestra",
        "name": "Phoenix Orchestra",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Phoenix Orchestra", "OT Phoenix Orchestra"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Contemporary Chinese chamber orchestra with 21 traditional instruments including erhu, guzheng, and pipa, developed in collaboration with Harry Gregson-Williams.",
        "price_type": "paid",
        "url": "https://www.orchestraltools.com/phoenix-orchestra",
        "year": 2020,
        "tags": ["orchestral", "cinematic", "film-scoring", "chinese", "world", "ethnic", "chamber", "sample-library"],
        "image_url": ""
    },
    {
        "slug": "ot-layers",
        "name": "Layers",
        "manufacturer_slug": "orchestral-tools",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST2", "VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Layers", "OT Layers", "Orchestral Tools Layers"],
        "daws": ["Bitwig", "Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Free orchestral instrument blending strings, woodwinds, and brass from flagship recordings with one-touch chord generation and seamless dynamic layering.",
        "price_type": "free",
        "url": "https://www.orchestraltools.com/layers",
        "year": 2020,
        "tags": ["orchestral", "strings", "woodwinds", "brass", "cinematic", "free", "starter", "sample-library"],
        "image_url": ""
    },
]

# ── McDSP plugins ────────────────────────────────────────────────────────

MCDSP_PLUGINS = [
    {
        "slug": "mcdsp-filterbank",
        "name": "FilterBank",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "eq",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["FilterBank", "McDSP FilterBank", "FilterBank E606", "FilterBank F202", "FilterBank P606"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Flagship equalizer comprising three plugins (E606, F202, P606) offering parametric EQ, steep filtering, and variable Q modes that emulate virtually any analog EQ.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/filterbank/",
        "year": 1998,
        "tags": ["eq", "parametric-eq", "analog-modeling", "mixing", "mastering", "vintage"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-compressorbank",
        "name": "CompressorBank",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "compressor",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["CompressorBank", "McDSP CompressorBank", "CB101", "CB202", "CB303"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "High-end compressor emulating vintage and modern designs with three configurations (CB101, CB202, CB303) offering adjustable compression curves.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/compressorbank/",
        "year": 2000,
        "tags": ["compressor", "analog-modeling", "dynamics", "mixing", "vintage"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-analog-channel",
        "name": "Analog Channel",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "saturation",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["Analog Channel", "McDSP Analog Channel", "AC101", "AC202"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Tape machine and channel amplifier emulation with analog pre-amp drive/saturation and tape bias, playback speed, and IEC equalization controls.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/analog-channel/",
        "year": 2004,
        "tags": ["saturation", "tape", "analog-modeling", "console", "preamp", "mixing", "warmth"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-mc2000",
        "name": "MC2000",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "multiband",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["MC2000", "McDSP MC2000"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Multi-band compressor with two, three, and four-band configurations, adjustable crossover filters, and multiple peak detection circuits.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/mc2000/",
        "year": 2003,
        "tags": ["compressor", "multiband", "dynamics", "mastering", "mixing", "analog-modeling"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-ml4000",
        "name": "ML4000",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "limiter",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["ML4000", "McDSP ML4000", "ML1", "ML4"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "High-resolution mastering limiter and multi-band dynamics processor for music, mastering, post-production, and live sound.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/ml4000/",
        "year": 2006,
        "tags": ["limiter", "mastering", "dynamics", "multiband", "brickwall", "loudness"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-revolver",
        "name": "Revolver",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "reverb",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["Revolver", "McDSP Revolver"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Convolution reverb with total impulse response control, dedicated routable EQ, sync-able delay lines, and three-band crossover for independent decay per frequency band.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/revolver/",
        "year": 2005,
        "tags": ["reverb", "convolution", "impulse-response", "mixing", "post-production", "spatial"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-channel-g",
        "name": "Channel G",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "channel-strip",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["Channel G", "McDSP Channel G", "G Console", "G Dynamics", "G Equalizer"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "TEC Award-nominated mixing console emulation modeling six large-format analog consoles with calibration modes for music and post-production.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/channel-g/",
        "year": 2007,
        "tags": ["channel-strip", "console", "analog-modeling", "eq", "compressor", "mixing"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-de555",
        "name": "DE555",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "de-esser",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["DE555", "McDSP DE555"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Advanced de-esser with intelligent signal analysis requiring no manual threshold adjustment, featuring HF-only mode and adjustable key filtering.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/de555/",
        "year": 2008,
        "tags": ["de-esser", "vocal", "dynamics", "sibilance", "mixing", "dialog"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-futzbox",
        "name": "FutzBox",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "lo-fi",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["FutzBox", "McDSP FutzBox"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Distortion and noise generator using Synthetic Impulse Models to simulate radios, cell phones, televisions, and other degraded audio sources.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/futzbox/",
        "year": 2008,
        "tags": ["distortion", "lo-fi", "sound-design", "noise", "creative", "post-production"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-nf575",
        "name": "NF575",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "filter",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["NF575", "McDSP NF575", "Noise Filter"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "High-resolution noise filter for eliminating rumble, hiss, and cyclical noise using selectable slopes up to 36 dB/Oct and five linkable notch filters.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/nf575/",
        "year": 2005,
        "tags": ["filter", "noise-reduction", "restoration", "notch", "post-production"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-6020-ultimate-eq",
        "name": "6020 Ultimate EQ",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "eq",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["6020", "6020 Ultimate EQ", "McDSP 6020"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Modular equalizer with interchangeable analog-modeled EQ modules offering a variety of classic EQ styles in a single interface.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/6020-ultimate/",
        "year": 2013,
        "tags": ["eq", "parametric-eq", "analog-modeling", "modular", "mixing", "vintage"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-6030-ultimate-compressor",
        "name": "6030 Ultimate Compressor",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "compressor",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["6030", "6030 Ultimate Compressor", "McDSP 6030"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Modular compressor featuring interchangeable modules that emulate classic hardware compressors in a wide range of styles.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/6030-ultimate/",
        "year": 2010,
        "tags": ["compressor", "analog-modeling", "dynamics", "modular", "mixing", "vintage"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-6050-ultimate-channel-strip",
        "name": "6050 Ultimate Channel Strip",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "channel-strip",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["6050", "6050 Ultimate Channel Strip", "McDSP 6050"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Modular channel strip combining 25+ interchangeable EQ and compressor modules with drag-and-drop signal flow and over 4,000 module combinations.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/6050-ultimate-channel-strip/",
        "year": 2016,
        "tags": ["channel-strip", "eq", "compressor", "modular", "mixing", "analog-modeling"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-6060-ultimate-module-collection",
        "name": "6060 Ultimate Module Collection",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "channel-strip",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["6060", "6060 Ultimate Module Collection", "McDSP 6060"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Largest module-based plugin with 30+ modules for EQ, compression, saturation, distortion, and gating with drag-and-drop arrangement and parallel processing.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/6060-ultimate-module-collection/",
        "year": 2019,
        "tags": ["channel-strip", "eq", "compressor", "modular", "mixing", "saturation", "analog-modeling"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-ae400",
        "name": "AE400",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "eq",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["AE400", "McDSP AE400", "AE400 Active EQ"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Four-band active equalizer with independent fixed and dynamic EQ modes per band, sidechain support, and selectable curves.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/ae400/",
        "year": 2013,
        "tags": ["eq", "dynamic-eq", "mixing", "mastering", "sidechain"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-ae600",
        "name": "AE600",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "eq",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["AE600", "McDSP AE600", "AE600 Active EQ"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Six-band active equalizer with independent fixed and dynamic EQ per band, parametric/vintage/shelving modes, and full sidechain support.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/ae600/",
        "year": 2016,
        "tags": ["eq", "dynamic-eq", "mixing", "mastering", "sidechain", "parametric-eq"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-ml8000",
        "name": "ML8000",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "limiter",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["ML8000", "McDSP ML8000"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Advanced multi-band limiter with dual processing stages, six selectable limiting modes, and moveable frequency bands for transparent mastering.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/ml8000/",
        "year": 2016,
        "tags": ["limiter", "mastering", "multiband", "loudness", "brickwall", "dynamics"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-sa-2",
        "name": "SA-2",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "eq",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["SA-2", "McDSP SA-2", "SA2", "Dialog Processor"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Emmy Award-winning dialog processor with five bands of strategic active equalization designed for speech and vocal processing.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/sa-2/",
        "year": 2015,
        "tags": ["dialog", "vocal", "eq", "post-production", "speech", "broadcast"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-ec-300",
        "name": "EC-300",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "delay",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["EC-300", "McDSP EC-300", "EC300", "Echo Collection"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Echo and chorus collection with magnetic, digital, and analog delay types featuring saturation, wow/flutter, ducking, and multiple routing modes.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/ec300-echo-collection/",
        "year": 2017,
        "tags": ["delay", "echo", "chorus", "analog-modeling", "tape-delay", "mixing", "creative"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-nr800",
        "name": "NR800",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "restoration",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["NR800", "McDSP NR800", "Noise Reduction"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Real-time eight-band noise reduction processor for cleaning dialog, reducing microphone bleed, and restoring compromised recordings.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/nr800/",
        "year": 2018,
        "tags": ["noise-reduction", "restoration", "dialog", "post-production", "broadcast"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-spc2000",
        "name": "SPC2000",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "compressor",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["SPC2000", "McDSP SPC2000"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Serial/parallel compressor with multiple routing configurations, analog-modeled compression curves, and dual time constant algorithms.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/spc2000/",
        "year": 2013,
        "tags": ["compressor", "serial", "parallel", "analog-modeling", "dynamics", "mixing"],
        "image_url": ""
    },
    {
        "slug": "mcdsp-sa-3",
        "name": "SA-3",
        "manufacturer_slug": "mcdsp",
        "category": "effect",
        "subcategory": "eq",
        "formats": ["AAX", "AU", "VST3"],
        "aliases": ["SA-3", "McDSP SA-3", "SA3", "Spectral Processor"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Advanced spectral processor with 1,000+ bands for detecting and eliminating persistent spectral peaks, with mid/side processing and programmable bias curves.",
        "price_type": "paid",
        "url": "https://mcdsp.com/plugin-index/sa-3/",
        "year": 2023,
        "tags": ["spectral", "eq", "dynamic-eq", "restoration", "dialog", "vocal", "mastering"],
        "image_url": ""
    },
]

# ── KORG plugins ─────────────────────────────────────────────────────────

KORG_DAWS = ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"]

KORG_PLUGINS = [
    {
        "slug": "korg-ms-20",
        "name": "KORG MS-20",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG MS-20", "MS-20 Plugin", "KORG Legacy MS-20", "MS20"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the iconic KORG MS-20 semi-modular analog synthesizer with dual oscillators, dual filters, and a virtual patch panel.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2004,
        "tags": ["synthesizer", "analog-modeling", "semi-modular", "vintage", "subtractive", "classic"],
        "image_url": ""
    },
    {
        "slug": "korg-polysix",
        "name": "KORG Polysix",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Polysix", "Polysix Plugin", "KORG Legacy Polysix"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Emulation of the classic 6-voice KORG Polysix polysynth upgraded to 32 voices with chorus, phaser, and ensemble effects.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2004,
        "tags": ["synthesizer", "analog-modeling", "polyphonic", "vintage", "pads", "classic"],
        "image_url": ""
    },
    {
        "slug": "korg-wavestation",
        "name": "KORG Wavestation",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Wavestation", "Wavestation Plugin", "KORG Legacy Wavestation"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the KORG Wavestation vector synthesizer with wave sequencing, 550 presets, and advanced modulation capabilities.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2004,
        "tags": ["synthesizer", "vector", "wave-sequencing", "vintage", "pads", "textures"],
        "image_url": ""
    },
    {
        "slug": "korg-m1",
        "name": "KORG M1",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG M1", "M1 Plugin", "KORG Legacy M1"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software version of the best-selling KORG M1 music workstation with 8-part multitimbrality, 256-note polyphony, and the iconic M1 Piano sound.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2006,
        "tags": ["synthesizer", "workstation", "rompler", "vintage", "classic", "piano"],
        "image_url": ""
    },
    {
        "slug": "korg-mono-poly",
        "name": "KORG Mono/Poly",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Mono/Poly", "Mono Poly Plugin", "MonoPoly"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Emulation of the four-oscillator KORG Mono/Poly with unison mode, cross-modulation, and upgraded polyphony for rich analog sounds.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2007,
        "tags": ["synthesizer", "analog-modeling", "vintage", "unison", "lead", "bass"],
        "image_url": ""
    },
    {
        "slug": "korg-arp-odyssey",
        "name": "KORG ARP Odyssey",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG ARP Odyssey", "ARP Odyssey Plugin", "ARP Odyssey VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the legendary ARP Odyssey duophonic synthesizer developed in collaboration with ARP co-founder David Friend.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2017,
        "tags": ["synthesizer", "analog-modeling", "vintage", "duophonic", "arp", "lead", "bass"],
        "image_url": ""
    },
    {
        "slug": "korg-triton",
        "name": "KORG TRITON",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG TRITON", "TRITON Plugin", "KORG Triton Extreme"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software version of the legendary KORG TRITON music workstation with 4,000 PCM presets, 256 voices, and the Triton Extreme's tube valve effect.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2020,
        "tags": ["synthesizer", "workstation", "rompler", "vintage", "classic", "pads"],
        "image_url": ""
    },
    {
        "slug": "korg-prophecy",
        "name": "KORG Prophecy",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Prophecy", "Prophecy Plugin"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the KORG Prophecy physical modeling synthesizer upgraded to 256-voice polyphony with comb filter, waveshaping, and VPM synthesis.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2021,
        "tags": ["synthesizer", "physical-modeling", "vintage", "lead", "experimental"],
        "image_url": ""
    },
    {
        "slug": "korg-minikorg-700s",
        "name": "KORG miniKORG 700S",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["miniKORG 700S", "KORG miniKORG", "miniKORG 700S Plugin"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of KORG's first synthesizer, the miniKORG 700S, with arpeggiator, modulation matrix, and the distinctive dual-filter architecture.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2021,
        "tags": ["synthesizer", "analog-modeling", "vintage", "monophonic", "classic"],
        "image_url": ""
    },
    {
        "slug": "korg-microkorg",
        "name": "KORG microKORG",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG microKORG", "microKORG Plugin", "microKORG VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software version of the iconic KORG microKORG analog-modeling synthesizer with vocoder, dual oscillators, and performance-oriented interface.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2022,
        "tags": ["synthesizer", "analog-modeling", "vocoder", "vintage", "electronic", "performance"],
        "image_url": ""
    },
    {
        "slug": "korg-arp-2600",
        "name": "KORG ARP 2600",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG ARP 2600", "ARP 2600 Plugin", "ARP 2600 VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the legendary ARP 2600 semi-modular synthesizer with new expansion modules, a spring reverb, and extensive patching capabilities.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2024,
        "tags": ["synthesizer", "semi-modular", "analog-modeling", "vintage", "arp", "experimental", "classic"],
        "image_url": ""
    },
    {
        "slug": "korg-ep-1",
        "name": "KORG EP-1",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "piano",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG EP-1", "EP-1 Plugin", "KORG Electric Piano"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Seven classic electric piano models from the KORG Kronos engine including Fender Rhodes, Wurlitzer, and Yamaha CP-inspired sounds.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2024,
        "tags": ["piano", "electric-piano", "rhodes", "wurlitzer", "vintage", "keys"],
        "image_url": ""
    },
    {
        "slug": "korg-ps-3300",
        "name": "KORG PS-3300",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG PS-3300", "PS-3300 Plugin", "PS3300"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the ultra-rare KORG PS-3300 fully polyphonic synthesizer, originally a massive semi-modular instrument with 48 VCOs.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2025,
        "tags": ["synthesizer", "analog-modeling", "polyphonic", "vintage", "rare", "classic", "semi-modular"],
        "image_url": ""
    },
    {
        "slug": "korg-trinity",
        "name": "KORG Trinity",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "rompler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Trinity", "Trinity Plugin", "Trinity VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software version of the KORG Trinity music workstation from the 1990s, a predecessor to the TRITON known for its high-quality PCM sounds and touch screen interface.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2025,
        "tags": ["synthesizer", "workstation", "rompler", "vintage", "classic"],
        "image_url": ""
    },
    {
        "slug": "korg-wavestate-native",
        "name": "KORG wavestate native",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX", "Standalone"],
        "aliases": ["wavestate native", "KORG wavestate", "wavestate VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Desktop plugin version of the KORG wavestate hardware synthesizer with Wave Sequencing 2.0 engine, four layers, and deep modulation architecture.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_wavestate_native/",
        "year": 2021,
        "tags": ["synthesizer", "wave-sequencing", "wavetable", "sound-design", "textures", "modern"],
        "image_url": ""
    },
    {
        "slug": "korg-opsix-native",
        "name": "KORG opsix native",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX", "Standalone"],
        "aliases": ["opsix native", "KORG opsix", "opsix VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Desktop plugin version of the KORG opsix hardware synthesizer featuring an altered FM synthesis engine with six operators and 30+ algorithm types.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_opsix_native/",
        "year": 2022,
        "tags": ["synthesizer", "fm-synthesis", "frequency-modulation", "sound-design", "modern"],
        "image_url": ""
    },
    {
        "slug": "korg-modwave-native",
        "name": "KORG modwave native",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX", "Standalone"],
        "aliases": ["modwave native", "KORG modwave", "modwave VST"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Desktop plugin version of the KORG modwave hardware wavetable synthesizer with dual wavetable layers, motion sequencing, and Kaoss Physics modulation.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_modwave_native/",
        "year": 2022,
        "tags": ["synthesizer", "wavetable", "sound-design", "modulation", "modern"],
        "image_url": ""
    },
    {
        "slug": "korg-multi-poly-native",
        "name": "KORG multi/poly native",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "AAX", "Standalone"],
        "aliases": ["multi/poly native", "KORG multi/poly", "multi poly native"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Desktop plugin version of the KORG multi/poly hardware synthesizer combining four independent synth layers with a motion engine and Kaoss Physics.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_multipoly_native/",
        "year": 2024,
        "tags": ["synthesizer", "multi-layer", "sound-design", "modulation", "modern"],
        "image_url": ""
    },
    {
        "slug": "korg-kaoss-pad",
        "name": "KORG Kaoss Pad",
        "manufacturer_slug": "korg",
        "category": "effect",
        "subcategory": "creative",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Kaoss Pad", "Kaoss Pad Plugin", "KP Plugin"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software version of the iconic KORG Kaoss Pad XY touchpad controller with real-time effects including filters, delays, modulation, and lo-fi processing.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2022,
        "tags": ["effects", "creative", "performance", "filter", "delay", "modulation", "xy-pad"],
        "image_url": ""
    },
    {
        "slug": "korg-electribe-r",
        "name": "KORG Electribe-R",
        "manufacturer_slug": "korg",
        "category": "instrument",
        "subcategory": "drum-machine",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["KORG Electribe-R", "Electribe-R Plugin", "KORG Electribe"],
        "daws": KORG_DAWS,
        "os": ["windows", "macos"],
        "description": "Software recreation of the KORG Electribe-R rhythm machine with analog-modeled percussion synthesis and step sequencing for electronic beat production.",
        "price_type": "paid",
        "url": "https://www.korg.com/us/products/software/korg_collection/",
        "year": 2022,
        "tags": ["drum-machine", "drums", "electronic", "beat-making", "sequencer", "vintage"],
        "image_url": ""
    },
]

# ── Vienna Symphonic Library plugins ──────────────────────────────────────

VSL_PLUGINS = [
    {
        "slug": "vsl-synchron-strings-pro",
        "name": "Synchron Strings Pro",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Strings Pro", "VSL Synchron Strings Pro", "VSL Strings Pro"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Next-generation sampled string ensembles recorded at Vienna Synchron Stage with detailed articulations, natural note transitions, and resource-efficient performance.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/strings-pro",
        "year": 2019,
        "tags": ["orchestral", "strings", "ensemble", "cinematic", "film-scoring", "sampler"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-brass",
        "name": "Synchron Brass",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Brass", "VSL Synchron Brass", "VSL Brass"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Orchestral brass library recorded at Vienna Synchron Stage with solo and ensemble sections including trumpets, French horns, trombones, cimbasso, and tubas.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/brass",
        "year": 2022,
        "tags": ["orchestral", "brass", "ensemble", "cinematic", "film-scoring", "sampler"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-woodwinds",
        "name": "Synchron Woodwinds",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Woodwinds", "VSL Synchron Woodwinds", "VSL Woodwinds"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Comprehensive orchestral woodwind library with piccolo, flute, oboe, English horn, clarinet, bass clarinet, bassoon, and contrabassoon as solo and ensemble instruments.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/woodwinds",
        "year": 2023,
        "tags": ["orchestral", "woodwinds", "ensemble", "cinematic", "film-scoring", "sampler"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-percussion",
        "name": "Synchron Percussion I",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Percussion I", "Synchron Percussion 1", "VSL Synchron Percussion"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Definitive orchestral percussion collection featuring timpani, drums, cymbals, gongs, mallets, bells, and more with multi-microphone Auro-3D capture at Synchron Stage.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/percussion-1",
        "year": 2017,
        "tags": ["orchestral", "percussion", "cinematic", "film-scoring", "sampler", "timpani", "drums", "cymbals"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-bosendorfer-imperial",
        "name": "Synchron Bosendorfer Imperial",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "piano",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Bosendorfer Imperial", "VSL Bosendorfer Imperial", "Vienna Imperial"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Meticulously sampled Bosendorfer Concert Grand 290 Imperial recorded at Synchron Stage with the full 97-key range and rich harmonic character.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/bosendorfer-imperial",
        "year": 2021,
        "tags": ["piano", "grand-piano", "acoustic-piano", "cinematic", "classical", "sampler", "concert-grand"],
        "image_url": ""
    },
    {
        "slug": "vsl-big-bang-orchestra",
        "name": "Big Bang Orchestra",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Big Bang Orchestra", "BBO", "VSL Big Bang Orchestra", "VSL BBO"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Complete orchestral ensemble library capturing the explosive sound of a full symphonic tutti with strings, brass, woodwinds, percussion, and choir sections.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/bbo-bundle",
        "year": 2019,
        "tags": ["orchestral", "ensemble", "cinematic", "film-scoring", "sampler", "epic", "tutti", "choir"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-duality-strings",
        "name": "Synchron Duality Strings",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Duality Strings", "VSL Duality Strings"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Dual-ensemble string library with two sections sampled simultaneously in separate rooms at Synchron Stage for unprecedented layering of intimate and expansive textures.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/duality-strings-regular",
        "year": 2021,
        "tags": ["orchestral", "strings", "ensemble", "cinematic", "film-scoring", "sampler", "layered"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-smart-orchestra",
        "name": "Synchron Smart Orchestra",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Smart Orchestra", "VSL Smart Orchestra"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Full orchestra in a single plugin combining strings, woodwinds, brass, percussion, and choir laid out across the keyboard for instant playability.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/smart-orchestra",
        "year": 2023,
        "tags": ["orchestral", "ensemble", "cinematic", "film-scoring", "sampler", "all-in-one"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-prime-orchestra",
        "name": "Synchron Prime Orchestra",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Prime Orchestra", "VSL Prime Orchestra"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Affordable entry point to VSL's Synchron series with essential strings, woodwinds, brass, percussion, and harp recorded at Synchron Stage Vienna.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/prime-orchestra",
        "year": 2025,
        "tags": ["orchestral", "ensemble", "cinematic", "film-scoring", "sampler", "starter"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-elite-strings",
        "name": "Synchron Elite Strings",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Elite Strings", "VSL Elite Strings"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Premium small-ensemble string library with hand-picked elite musicians providing intimate and highly expressive performances recorded at Synchron Stage.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/synchron/elite-strings",
        "year": 2020,
        "tags": ["orchestral", "strings", "ensemble", "cinematic", "film-scoring", "sampler", "chamber"],
        "image_url": ""
    },
    {
        "slug": "vsl-vienna-ensemble-pro",
        "name": "Vienna Ensemble Pro",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "utility",
        "subcategory": "host",
        "formats": ["VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Vienna Ensemble Pro", "VE Pro", "VEP", "Vienna Ensemble Pro 8"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Industry-standard network-compatible mixing host connecting virtual instruments and multiple computers into one workflow with crash protection and performance monitoring.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/software/vienna-ensemble-pro-8",
        "year": 2009,
        "tags": ["host", "mixing", "networking", "workflow", "orchestral", "template", "server"],
        "image_url": ""
    },
    {
        "slug": "vsl-mir-pro-3d",
        "name": "Vienna MIR Pro 3D",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "effect",
        "subcategory": "reverb",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Vienna MIR Pro 3D", "MIR Pro", "Vienna MIR", "Multi Impulse Response"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Advanced Multi Impulse Response convolution reverb supporting stereo, surround, and immersive 3D audio with Ambisonics and virtual stage positioning in real concert halls.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/software/vienna-mir-pro-3d",
        "year": 2022,
        "tags": ["reverb", "convolution", "immersive", "surround", "3d-audio", "ambisonics", "spatial-audio", "orchestral"],
        "image_url": ""
    },
    {
        "slug": "vsl-synchron-stage-reverb",
        "name": "Synchron Stage Reverb",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "effect",
        "subcategory": "reverb",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Synchron Stage Reverb", "VSL Stage Reverb"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Convolution reverb recreating the ambience of Stage A at Vienna Synchron Stage using impulse responses from the same Decca Tree setup used in professional scoring sessions.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/software/synchron-stage-reverb",
        "year": 2022,
        "tags": ["reverb", "convolution", "cinematic", "film-scoring", "orchestral", "surround", "mixing"],
        "image_url": ""
    },
    {
        "slug": "vsl-vienna-suite-pro",
        "name": "Vienna Suite Pro",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "effect",
        "subcategory": "general",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Vienna Suite Pro", "VSL Suite Pro", "Vienna Suite"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Collection of eleven audio processing plugins including EQ, compressor, limiter, exciter, convolution reverb, hybrid reverb, analyzer, and monitoring tools.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/software/vienna-suite-pro",
        "year": 2009,
        "tags": ["effects-suite", "eq", "compressor", "limiter", "reverb", "analyzer", "mixing", "mastering"],
        "image_url": ""
    },
    {
        "slug": "vsl-studio-special-edition",
        "name": "Studio Special Edition Vol. 1",
        "manufacturer_slug": "vienna-symphonic-library",
        "category": "instrument",
        "subcategory": "sampler",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["Studio Special Edition Vol. 1", "VSL Special Edition", "VSL SE Vol 1"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Essential orchestra collection with 50+ instruments and ensembles including strings, brass, woodwinds, percussion, harp, and pianos recorded at VSL's Silent Stage.",
        "price_type": "paid",
        "url": "https://www.vsl.co.at/products/studio/special-edition-vol-1",
        "year": 2018,
        "tags": ["orchestral", "ensemble", "cinematic", "film-scoring", "sampler", "starter", "all-in-one"],
        "image_url": ""
    },
]

# ── Moog Music plugins ───────────────────────────────────────────────────

MOOG_PLUGINS = [
    {
        "slug": "moog-mariana",
        "name": "Mariana",
        "manufacturer_slug": "moog-music",
        "category": "instrument",
        "subcategory": "bass-synth",
        "formats": ["VST3", "AU", "AAX", "Standalone"],
        "aliases": ["Moog Mariana", "Mariana Bass Synthesizer"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Dual-layer bass synthesizer with parallel filtering, cross-layer modulation, built-in compression, saturation, and virtual CV connectivity to Moogerfooger effects.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mariana",
        "year": 2023,
        "tags": ["synthesizer", "bass", "analog-modeling", "moog", "modulation"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-101s",
        "name": "Moogerfooger MF-101S Lowpass Filter",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "filter",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-101S", "Moogerfooger Lowpass Filter"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Classic Moog ladder lowpass filter with envelope follower for dynamic filtering, stereo operation, and virtual CV interconnectivity.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-101s",
        "year": 2022,
        "tags": ["filter", "lowpass", "moog", "analog-modeling", "envelope-follower", "moogerfooger", "vintage"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-102s",
        "name": "Moogerfooger MF-102S Ring Modulator",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "modulation",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-102S", "Moogerfooger Ring Modulator"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Wide-range carrier oscillator paired with an LFO for effects from subtle tremolo to metallic ring modulation, with stereo operation and virtual CV.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-102s",
        "year": 2022,
        "tags": ["ring-modulator", "modulation", "moog", "analog-modeling", "tremolo", "moogerfooger", "vintage"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-103s",
        "name": "Moogerfooger MF-103S 12-Stage Phaser",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "modulation",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-103S", "Moogerfooger Phaser"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Descendant of the 1970s Moog phaser with 6-stage and 12-stage modes, onboard LFO, stereo operation, and virtual CV connectivity.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-103s",
        "year": 2022,
        "tags": ["phaser", "modulation", "moog", "analog-modeling", "moogerfooger", "vintage"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-104s",
        "name": "Moogerfooger MF-104S Analog Delay",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "delay",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-104S", "Moogerfooger Analog Delay"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Rich bucket-brigade-style analog delay with warm organic texture, modulation controls, stereo operation, and virtual CV interconnectivity.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-104s",
        "year": 2022,
        "tags": ["delay", "analog-delay", "moog", "analog-modeling", "moogerfooger", "vintage"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-105s",
        "name": "Moogerfooger MF-105S MuRF",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "creative",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-105S", "Moogerfooger MuRF", "Multiple Resonance Filter Array"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Multiple Resonance Filter Array combining a resonant filter bank with a pattern generator and skewing envelope for rhythmic, animated filtering.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-105s",
        "year": 2022,
        "tags": ["filter", "resonant", "pattern", "moog", "analog-modeling", "moogerfooger", "experimental"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-107s",
        "name": "Moogerfooger MF-107S FreqBox",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "creative",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-107S", "Moogerfooger FreqBox"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Unconventional effect processor with a synced VCO, envelope follower, and FM modulation for experimental frequency modulation sounds.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-107s",
        "year": 2022,
        "tags": ["frequency-modulation", "fm", "moog", "analog-modeling", "moogerfooger", "experimental"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-108s",
        "name": "Moogerfooger MF-108S Cluster Flux",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "chorus",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-108S", "Moogerfooger Cluster Flux"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Flexible time-modulation processor that smoothly transitions between chorus, flanging, and vibrato effects with stereo operation and virtual CV.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-108s",
        "year": 2022,
        "tags": ["chorus", "flanger", "vibrato", "moog", "analog-modeling", "moogerfooger", "modulation", "vintage"],
        "image_url": ""
    },
    {
        "slug": "moogerfooger-mf-109s",
        "name": "Moogerfooger MF-109S Saturator",
        "manufacturer_slug": "moog-music",
        "category": "effect",
        "subcategory": "saturation",
        "formats": ["VST3", "AU", "AAX"],
        "aliases": ["MF-109S", "Moogerfooger Saturator"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic", "Pro Tools"],
        "os": ["windows", "macos"],
        "description": "Saturation effect based on the Moogerfooger input drive circuit with wide-range envelope follower and bipolar drive control for warmth and distortion.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/store/mf-109s",
        "year": 2022,
        "tags": ["saturation", "distortion", "moog", "analog-modeling", "moogerfooger", "warmth"],
        "image_url": ""
    },
    {
        "slug": "moog-minimoog-model-d",
        "name": "Minimoog Model D",
        "manufacturer_slug": "moog-music",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "Standalone"],
        "aliases": ["Moog Model D", "Minimoog Model D App", "Model D"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic"],
        "os": ["macos"],
        "description": "Software recreation of the iconic Minimoog Model D with 4-note polyphony, arpeggiator, stereo ping-pong delay, and the Bender time-modulation effect.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/synthesizers",
        "year": 2022,
        "tags": ["synthesizer", "analog-modeling", "moog", "minimoog", "vintage", "bass", "lead", "classic"],
        "image_url": ""
    },
    {
        "slug": "moog-model-15",
        "name": "Model 15",
        "manufacturer_slug": "moog-music",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "Standalone"],
        "aliases": ["Moog Model 15", "Model 15 Modular Synthesizer"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic"],
        "os": ["macos"],
        "description": "Faithful recreation of the 1970s Moog Model 15 modular synthesizer with patchable modules, 4-voice polyphony, sequencer, and performance controllers.",
        "price_type": "paid",
        "url": "https://software.moogmusic.com/synthesizers",
        "year": 2021,
        "tags": ["synthesizer", "modular", "moog", "vintage", "analog-modeling", "experimental"],
        "image_url": ""
    },
    {
        "slug": "moog-animoog-z",
        "name": "Animoog Z",
        "manufacturer_slug": "moog-music",
        "category": "instrument",
        "subcategory": "synth",
        "formats": ["VST3", "AU", "Standalone"],
        "aliases": ["Moog Animoog Z", "Animoog Z Synthesizer"],
        "daws": ["Ableton", "Cubase", "Studio One", "Reaper", "FL Studio", "Logic"],
        "os": ["macos"],
        "description": "16-voice polyphonic synthesizer powered by Moog's Anisotropic Synth Engine using a novel orbit system for multidimensional wavetable and vector synthesis.",
        "price_type": "freemium",
        "url": "https://software.moogmusic.com/synthesizers",
        "year": 2021,
        "tags": ["synthesizer", "wavetable", "moog", "polyphonic", "sound-design", "experimental"],
        "image_url": ""
    },
]


def main():
    with open(SEED_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    existing_mfr_slugs = {m["slug"] for m in data["manufacturers"]}
    existing_plugin_slugs = {p["slug"] for p in data["plugins"]}

    # Add manufacturers (maintaining alphabetical sort)
    added_mfrs = 0
    for mfr in NEW_MANUFACTURERS:
        if mfr["slug"] not in existing_mfr_slugs:
            data["manufacturers"].append(mfr)
            existing_mfr_slugs.add(mfr["slug"])
            added_mfrs += 1
            print(f"  + manufacturer: {mfr['name']}")
    data["manufacturers"].sort(key=lambda m: m["slug"])

    # Add plugins
    all_new_plugins = OT_PLUGINS + MCDSP_PLUGINS + KORG_PLUGINS + VSL_PLUGINS + MOOG_PLUGINS
    added_plugins = 0
    skipped = 0
    for plugin in all_new_plugins:
        if plugin["slug"] in existing_plugin_slugs:
            print(f"  SKIP (duplicate slug): {plugin['slug']}")
            skipped += 1
            continue
        # Verify manufacturer exists
        if plugin["manufacturer_slug"] not in existing_mfr_slugs:
            print(f"  ERROR: unknown manufacturer {plugin['manufacturer_slug']} for {plugin['slug']}")
            continue
        data["plugins"].append(plugin)
        existing_plugin_slugs.add(plugin["slug"])
        added_plugins += 1

    with open(SEED_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"\nDone: +{added_mfrs} manufacturers, +{added_plugins} plugins ({skipped} skipped)")
    print(f"Total: {len(data['manufacturers'])} manufacturers, {len(data['plugins'])} plugins")


if __name__ == "__main__":
    main()
